function interfata(Vplus, Vminus, A, A0, f,faza, N, R1, R2,semnal)

%Fereastra 
figure('Name','Amplificatorul operational inversor',...
    'Units','normalized',...
    'Position',[0.05 0.05 0.8 0.85],...
    'Color','white',...
    'NumberTitle','off');


%Titlu
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.18 0.8 0.6 0.2],...
        'BackgroundColor','white',...
        'foregroundcolor','black',...
        'FontSize',25,...
        'String','Amplificator operational inversor');

%Alimentare AO
Alim=uibuttongroup('Visible','on',...
        'BackgroundColor','white',...
        'ForegroundColor','black',...
        'Title','Alimentare AO',...
        'FontSize',12,...
        'Position',[0.05 0.75 0.2 0.15],...
        'TitlePosition','centertop',...
        'Tag','radiobutton');
  
% Alimentarea negativa
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.65 0.4 0.27],...
        'backgroundcolor',[0.4 0.4 0.4],...
        'foregroundcolor','white',...
        'FontSize',12,...
        'String','-V[V]',...
        'Parent',Alim);

uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.58 0.65 0.35 0.27],...
        'FontSize',12,...
        'FontWeight','Bold',...
        'String',Vminus,...
        'Parent',Alim,...
        'Callback',['Vminus=','str2num(get(gco,''String'')),close,interfata(Vplus,Vminus,A,A0,f,faza,N,R1,R2,semnal)']);

% Alimentarea pozitiva
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.3 0.4 0.27],...
        'backgroundcolor',[0.4 0.4 0.4],...
        'foregroundcolor','white',...
        'FontSize',12,...
        'String','+V[V]',...
        'Parent',Alim);

uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.58 0.3 0.35 0.27],...
        'FontSize',12,...
        'FontWeight','Bold',...
        'String',Vplus,...
        'Parent',Alim,...
        'Callback',['Vplus=','str2num(get(gco,''String'')),close,interfata(Vplus,Vminus,A,A0,f,faza, N,R1,R2,semnal)']);

%Dimensionarea rezistentelor
R=uibuttongroup('Visible','on',...
        'BackgroundColor','white',...
        'ForegroundColor','black',...
        'Title','Dimensionarea rezistentelor',...
        'FontSize',13,...
        'Position',[0.05 0.58 0.2 0.15],...
        'TitlePosition','centertop',...
        'Tag','radiobutton');
% R1
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.65 0.4 0.27],...
        'backgroundcolor',[0.4 0.4 0.4],...
        'foregroundcolor','white',...
        'FontSize',12,...
        'String','R1',...
        'Parent',R);

uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.58 0.65 0.35 0.27],...
        'FontSize',12,...
        'FontWeight','Bold',...
        'String',R1,...
        'Parent',R,...
        'Callback',['R1=','str2num(get(gco,''String'')),close,interfata(Vplus,Vminus,A,A0,f,faza, N,R1,R2,semnal)']);

% R2
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.3 0.4 0.27],...
        'backgroundcolor',[0.4 0.4 0.4],...
        'foregroundcolor','white',...
        'FontSize',12,...
        'String','R2',...
        'Parent', R);

uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.58 0.3 0.35 0.27],...
        'FontSize',12,...
        'FontWeight','Bold',...
        'String',R2,...
        'Parent',R,...
        'Callback',['R2=','str2num(get(gco,''String'')),close,interfata(Vplus,Vminus,A,A0,f,faza,N,R1,R2,semnal)']);


%Semnalul de intrare
BT=uibuttongroup('Visible','on',...
        'BackgroundColor','white',...
        'ForegroundColor','black',...
        'Title','Tensiunea de intrare',...
        'FontSize',13,...
        'Position',[0.05 0.26 0.2 0.3],...
        'TitlePosition','centertop',...
        'Tag','radiobutton');

%componenta continua a semnalului de intrare
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.68 0.4 0.16],...
        'backgroundcolor',[0.4 0.4 0.4],...
        'foregroundcolor','white',...
        'FontSize',12,...
        'String','A0[V]',...
        'Parent',BT);

uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.58 0.68 0.35 0.16],...
        'FontSize',12,...
        'FontWeight','Bold',...
        'String',A0,...
        'Parent',BT,...
        'Callback',['A0=','str2num(get(gco,''String'')),close,interfata(Vplus,Vminus,A,A0,f,faza,N,R1,R2,semnal)']);

% Amplitudinea semnalului de intrare
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.48 0.4 0.16],...
        'backgroundcolor',[0.4 0.4 0.4],...
        'foregroundcolor','white',...
        'FontSize',12,...
        'String','A',...
        'Parent', BT);

uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.58 0.48 0.35 0.16],...
        'FontSize',12,...
        'FontWeight','Bold',...
        'String',A,...
        'Parent',BT,...
        'Callback',['A=','str2num(get(gco,''String'')),close,interfata(Vplus,Vminus,A,A0,f,faza,N,R1,R2,semnal)']);

% Frecventa semnalului de intrare
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.28 0.4 0.16],...
        'backgroundcolor',[0.4 0.4 0.4],...
        'foregroundcolor','white',...
        'FontSize',12,...
        'String','f[Hz]',...
        'Parent', BT);

uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.58 0.28 0.35 0.16],...
        'FontSize',12,...
        'FontWeight','Bold',...
        'String',f,...
        'Parent',BT,...
        'Callback',['f=','str2num(get(gco,''String'')),close,interfata(Vplus,Vminus,A,A0,f,faza,N,R1,R2,semnal)']);

% Defazajul semnalului de intrare
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.08 0.41 0.17],...
        'backgroundcolor',[0.4 0.4 0.4],...
        'foregroundcolor','white',...
        'FontSize',12,...
        'String','defazaj[deg]',...
        'Parent', BT);

uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.58 0.08 0.35 0.16],...
        'FontSize',12,...
        'FontWeight','Bold',...
        'String',faza,...
        'Parent',BT,...
        'Callback',['faza=','str2num(get(gco,''String'')),' ...
        'close,interfata(Vplus,Vminus,A,A0,f,faza,N,R1,R2,semnal)']);


% Tipul semnalului
uicontrol('Style','PopupMenu',...
               'Units','normalized',...
               'Position',[0.1 0.6 0.8 0.4],...
               'Parent',BT,...
               'String','Sinus|Triunghi|Dinte fierastrau|Dreptunghi',...
               'Value',semnal,...
               'Callback','semnal=get(gco,''Value'');close;interfata(Vplus,Vminus,A,A0,f,faza,N,R1,R2,semnal)'); 

%Reprezentare
BR=uibuttongroup('Visible','on',...
        'BackgroundColor','white',...
        'ForegroundColor','black',...
        'Title','Reprezentare',...
        'FontSize',13,...
        'Position',[0.05 0.11 0.2 0.13],...
        'TitlePosition','centertop',...
        'Tag','radiobutton');

%nr de perioade afisate
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.5 0.4 0.4],...
        'backgroundcolor',[0.4 0.4 0.4],...
        'foregroundcolor','white',...
        'FontSize',12,...
        'String','Nr.perioade',...
        'Parent',BR);

uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.58 0.5 0.35 0.4],...
        'FontSize',12,...
        'FontWeight','Bold',...
        'String',N,...
        'Parent',BR,...
        'Callback',['N=','str2num(get(gco,''String'')),close,interfata(Vplus,Vminus,A,A0,f,faza,N,R1,R2,semnal)']);

%Grafic
BG=uibuttongroup('Visible','on',...
        'BackgroundColor','white',...
        'ForegroundColor','black',...
        'Title','Reprezentare grafica',...
        'FontSize',13,...
        'Position',[0.27 0.4 0.5 0.5],...
        'TitlePosition','centertop',...
        'Tag','radiobutton');

subplot('Position', [0.1 0.1 0.8 0.9],...
    'Parent', BG);
T=1/f;
t=0:T/100:N*T;
nt=length(t);
rad=deg2rad(faza);

switch(semnal) 
    case 1 %Sinusoidal
      Vi=A0+A.*sin(2.*pi.*f.*t+rad);  
        
    case 2 %Triunghiular
        Vi=A0+(2*A/pi)*asin(sin(2.*pi.*f.*t+rad));
    
    case 3 %Dinte fierastrau
        Vi= A0+(2*A/pi)*atan(tan(2.*pi.*f.*t+rad));

    otherwise %Dreptunghiular
        Vi=A0+A*sign(sin(2*pi*100*t+rad));

end

subplot('position',[0.1 0.15 0.85 0.8],...
            'Parent',BG);
        plot(t,Vi,'color','black','LineWidth',2);
        hold on;
        grid on;
        xlabel('timp [ms]');
        ylabel('Amplitudine [V]');

%Amplificarea semnalului de iesire
 Av=-R2/R1;
 
%%%%%%%%%% Calculul semnalului de iesire %%%%%%
Vo=zeros(1,nt);
for k=1:nt 
         Vo(k)=A0+Av*Vi(k);
         if Vo(k)<Vminus
            Vo(k)=Vminus;
        elseif Vo(k)>Vplus
            Vo(k)=Vplus;
         end
end
    
%%% Reprezentarea grafica a Vo
    subplot('position',[0.1 0.15 0.85 0.8]);
    plot(t,Vo,'color','red','LineWidth',2);
    grid on;
    xlabel('timp [ms]');
    ylabel('Amplitudine [V]');
    line('XData', [0 N*T], 'YData', [Vplus Vplus], 'LineStyle', ':', ...  %Maxinul Amplificarii
          'LineWidth', 2, 'Color','b');
    line('XData', [0 N*T], 'YData', [Vminus Vminus], 'LineStyle', ':', ...%Minimul Amplificarii
          'LineWidth', 2, 'Color','b');

    %Legenda grafic:
 legend('Vi','V0');


 %%%%%%%   Grafic CSTV V0(Vi) %%%%%%%%

 CSTV=uibuttongroup('Visible','on',...
        'BackgroundColor','white',...
        'ForegroundColor','black',...
        'Title','CSTV Vo(Vi)',...
        'FontSize',13,...
        'Position',[0.27 0.01 0.3 0.39],...
        'TitlePosition','centertop',...
        'Tag','radiobutton');
subplot('position',[0.13 0.18 0.85 0.8],...
            'Parent',CSTV);

plot(Vi,Vo,'-r',LineWidth=2);
xlabel('Vi[V]');
ylabel('Vo[V]');
grid on;
hold on;


%imagine/Schema circuitului
IM=uibuttongroup('Visible','on',...
        'BackgroundColor','white',...
        'ForegroundColor','black',...
        'Title','Schema electrica',...
        'FontSize',13,...
        'Position',[0.58 0.01 0.4 0.39],...
        'TitlePosition','centertop',...
        'Tag','radiobutton');
img=imread('AOInversor.jpg');
subplot('Position',[0.01 0.01 0.99 0.99],...
    'Parent',IM);
imshow(img);

%%%%%%%%%    Rezultate finale   %%%%%%%%%
Rez=uibuttongroup('Visible','on',...
        'BackgroundColor','white',...
        'ForegroundColor','black',...
        'Title','Rezultate',...
        'FontSize',13,...
        'Position',[0.78 0.4 0.2 0.2],...
        'TitlePosition','centertop',...
        'Tag','radiobutton');

uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.01 0.55 0.5 0.2],...
        'String',['Av = ',num2str(Av)],...
        'BackgroundColor','white',...
        'FontSize',12,...
        'FontWeight','bold',...
        'Parent',Rez);


%%%%%%  Limitari pt AO %%%%%

mesaj= "Valoare tensiunii nu se incadreaza in limitele de functionare!";
suma = Vminus+Vplus;
if(suma<-5 || suma>30)
    error(mesaj);
end

mesaj ="Valoarea rezistentelor nu poate fi negativa!";
if(R1<1 || R2<1)
    error(mesaj);
end

mesaj = "Faza unui semnal trebuie sa fie cuprinsa intre 0-360 grade!";
if(faza<0 || faza >360)
    error(mesaj);
end

mesaj ="Frecventa nu poate fi negativa!";
if(f<=0)
    error(mesaj);
end

%%%%%

%%%%%  Buton RESET %%%%%

uicontrol('Style','pushbutton',... 
'Units','normalized',...
'Position',[0.05 0.04 0.08 .05],...
'BackgroundColor',[0, 0.75, 0.75],...
'FontWeight','bold',...
'string','RESET',...
'Callback','close,interfata(15, -15, 5, 0, 5000,0, 3, 1000, 5000,1)');

%%%%%  Buton CLOSE %%%%%

uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.15 0.04 0.08 .05],...
'BackgroundColor',[0, 0.75, 0.75],...
'ForegroundColor','black',...
'FontWeight','bold',...
'string','CLOSE',...
'Callback','close');


%%%%%%%  Butoane MENIU %%%%%%%%
uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.8 0.85 0.15 .05],...
'BackgroundColor',[0, 0.75, 0.75],...
'ForegroundColor','black',...
'FontWeight','bold',...
'string','Prezentare',...
'Callback','open("Prezentare.pptx")');

uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.8 0.78 0.15 .05],...
'BackgroundColor',[0, 0.75, 0.75],...
'ForegroundColor','black',...
'FontWeight','bold',...
'string','Parte teoretica',...
'Callback','open("Teorie.pdf")');


uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.8 0.71 0.15 .05],...
'BackgroundColor',[0, 0.75, 0.75],...
'ForegroundColor','black',...
'FontWeight','bold',...
'string','Autor',...
'Callback','open("Autor.pdf")');


uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.8 0.64 0.15 .05],...
'BackgroundColor',[0, 0.75, 0.75],...
'ForegroundColor','black',...
'FontWeight','bold',...
'string','Bibliografie',...
'Callback','open("Bibliografie.pdf")');